#!/bin/bash

MICROSOFT_CASK=(
  microsoft-office 
  microsoft-lync
  remote-desktop-connection
)
MICROSOFT_BREW=(
  azure-cli
)

brew cask install ${MICROSOFT_CASK[@]}
brew install ${MICROSOFT_BREW[@]}

