#!/bin/bash
# Taken from https://github.com/soffes/dotfiles/

DOTFILES_ROOT="$HOME/.dotfiles"
RUBY_VERSION="2.3.1"
echo "--> Starting post setup script"

# Set hostname
printf "Enter computer name: "
read -r name
sudo scutil --set LocalHostName $name
sudo scutil --set ComputerName $name
sudo scutil --set HostName $name

echo "--> Writing defaults"
# Finder
# Natural scroll
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
# Turn off mounted drive desktop icons
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
# Turn off change extension warning
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
# Show all file extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Dock
# Minimize app to icon
defaults write com.apple.dock minimize-to-application -bool true
# Put dock on the left
defaults write com.apple.dock orientation left
# Auto-hide dock
defaults write com.apple.dock autohide-time-modifier -int 0

# Modifier Keys
# Set caps lock to control
defaults -currentHost write -g com.apple.keyboard.modifiermapping.1452-627-0 -array-add '<dict><key>HIDKeyboardModifierMappingDst</key><integer>2</integer><key>HIDKeyboardModifierMappingSrc</key><integer>0</integer></dict>'

echo "--> Symlinking macvim"
ln -fs /usr/local/bin/mvim /usr/local/bin/vi
ln -fs /usr/local/bin/mvim /usr/local/bin/vim
ln -fs /usr/local/opt/macvim/bin/mvim /usr/local/bin/mvim

echo "--> Symlinking bin folder…"
ln -fs $HOME/.dotfiles/bin $HOME/bin

echo "--> Symlinking config files"
ln -fs $DOTFILES_ROOT/vimrc $HOME/.vimrc
ln -fs $DOTFILES_ROOT/gitconfig $HOME/.gitconfig
ln -fs $DOTFILES_ROOT/gitignore_global $HOME/.gitignore_global
ln -fs $DOTFILES_ROOT/zshrc $HOME/.zshrc
ln -fs $DOTFILES_ROOT/gemrc $HOME/.gemrc
ln -fs $DOTFILES_ROOT/ctags $HOME/.ctags
ln -fs $DOTFILES_ROOT/tmux.conf $HOME/.tmux.conf

echo "--> Installing oh-my-zsh"
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

echo "--> Installing Ruby $RUBY_VERSION"
rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION

source $HOME/.zshrc

GEMS=(
    bundler
    cocoapods
    fastlane
    xcpretty
)
echo "--> Installing gems"
rbenv shell $RUBY_VERSION
gem install ${GEMS[@]}

echo "--> Installing vim themes"
for i in $DOTFILES_ROOT/themes/vim/*; do
  ln -fs "$i" $HOME/.vim/colors
done

echo "--> Installing fonts"
for i in $DOTFILES_ROOT/fonts/*; do
  cp -v "$i" $HOME/Library/Fonts
done

echo "--> Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "--> Installing vim plugins"
mvim +PlugUpdate
