#!/bin/bash
# Taken from https://github.com/soffes/dotfiles/

DOTFILES_ROOT="$HOME/.dotfiles"
RUBY_VERSION="2.3.1"
echo "--> Starting post setup script"
#echo "--> Changing shell"
#chsh -s /usr/local/bin/zsh

# Turn off natual scrolling
echo "--> Writing defaults"
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

echo "--> Symlinking macvim"
ln -fs /usr/local/bin/mvim /usr/local/bin/vi
ln -fs /usr/local/bin/mvim /usr/local/bin/vim

echo "--> Symlinking bin folder…"
ln -fs $HOME/.dotfiles/bin $HOME/bin

echo "--> Symlinking config files"
ln -fs $DOTFILES_ROOT/vimrc $HOME/.vimrc
ln -fs $DOTFILES_ROOT/gitconfig $HOME/.gitconfig
ln -fs $DOTFILES_ROOT/gitignore_global $HOME/.gitignore_global
ln -fs $DOTFILES_ROOT/zshrc $HOME/.zshrc
ln -fs $DOTFILES_ROOT/gemrc $HOME/.gemrc
ln -fs $DOTFILES_ROOT/ctags $HOME/.ctags
ln -fs $DOTFILES_ROOT/tmux.conf $HOME/.tmux.conf

echo "--> Installing oh-my-zsh"
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

echo "--> Installing Ruby $RUBY_VERSION"
rbenv install $RUBY_VERSION
rbenv global $RUBY_VERSION

source $HOME/.zshrc

GEMS=(
    bundler
    cocoapods
    fastlane
    xcpretty
)
echo "--> Installing gems"
rbenv shell $RUBY_VERSION
gem install  ${GEMS[@]}

echo "--> Installing vim themes"
ln -fs $DOTFILES_ROOT/themes/vim $HOME/.vim/colors 

echo "--> Installing fonts"
for i in $DOTFILES_ROOT/fonts/*; do
  cp -v "$i" $HOME/Library/Fonts
done

echo "--> Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "--> Installing vim plugins"
mvim +PlugUpdate
