#!/bin/bash
# Taken from https://github.com/soffes/dotfiles/

DOTFILES_ROOT="$HOME/dotfiles"

echo "Changing shell…"
chsh -s /usr/local/bin/zsh

echo "Symlinking macvim…"
ln -s /usr/local/bin/mvim /usr/local/bin/vi
ln -s /usr/local/bin/mvim /usr/local/bin/vim

echo "Symlinking config files"
ln -s $DOTFILES_ROOT/vimrc $HOME/.vimrc
ln -s $DOTFILES_ROOT/gitconfig $HOME/.gitconfig
ln -s $DOTFILES_ROOT/gitignore_global $HOME/.gitignore_global
ln -s $DOTFILES_ROOT/zshrc $HOME/.zshrc
ln -s $DOTFILES_ROOT/gemrc $HOME/.gemrc
ln -s $DOTFILES_ROOT/tmux.conf $HOME/.tmux.conf

echo "Installing Ruby…"
rbenv install 2.3.1
rbenv global 2.3.1

GEMS=(
    bundler
    cocoapods
    fastlane
    xcpretty
)
echo "Installing gems…"
gem install  ${GEMS[@]}

echo "Installing vim-plug…"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing vim plugins…"
mvim +PlugUpdate

# Turn off natual scrolling
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

echo "Done."
